<?php

namespace app\components;

use yii\base\Widget;
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use app\models\Content;
use yii\bootstrap\ActiveForm;

class IndexWidget extends Widget
{

    public $a;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if($this->a === null){$this->a = 0;}
    }

    public function run()
    {
        if($this->a == 0){
            return $text = 'Ошибка';
        }
        $model = Content::findOne(1);
        //Выводим левый текст шапки из бд с проверкой по номеру 1
        if($this->a == 1){
            return $header_block = HtmlPurifier::process($model->header_block);
        }
        //Выводим правый текст шапки (номер и почта) из бд с проверкой по номеру 2
        if($this->a == 2){
            return $header_block = HtmlPurifier::process($model->header_block_tel);
        }

        //Выводим ссылку на вк из бд с проверкой по номеру 4
        if($this->a == 4){
            if($model->footer_social_vk == null){$model->footer_social_vk = '';}
            return $social_vk = Html::encode($model->footer_social_vk);
        }
        //Выводим ссылку на ютуб (пример, user/barcroftmedia) с проверкой по номеру 5
        if($this->a == 5){
            if($model->footer_social_youtube == null){$model->footer_social_youtube = '#';}
            return $social_youtube = Html::encode($model->footer_social_youtube);
        }
        //Выводим текст с номером и временем работы в футере шаблона po 3
        if($this->a == 3){
            if($model->footer_contact == null){$model->footer_contact = 'Текст футера';}
            return $footer_contact = HtmlPurifier::process($model->footer_contact);
        }

        return $text = 'Ошибка';
    }
}